/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package plataforma_multiagente.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SpringLayout;
import plataforma_multiagente.EntornoLocal;

/**
 *
 * @author usuario
 */
public class PanelLogin extends javax.swing.JPanel {
    GUI padre;
    JButton enviar;
    JLabel nombre;
    JLabel contrasena;
    JTextField fnombre;
    JTextField fcontrasena;
    SpringLayout layout;
    /**
     * Creates new form PanelLogin
     */
    public PanelLogin(GUI padre) {
        this.padre = padre;
        layout = new SpringLayout();
        this.setLayout(layout);
        //Etiquetas
        nombre = new JLabel("ID usuario");
        contrasena = new JLabel("contraseña");
        this.add(nombre);
        this.add(contrasena);
        //Campos de texto
        this.fnombre = new JTextField(15);
        this.fcontrasena = new JTextField(15);
        this.add(fnombre);
        this.add(fcontrasena);
        //Boton
        enviar = new JButton("enviar");
        this.add(enviar);
        
        this.configureLayout();
        
        enviar.addActionListener(new EnviarPress());
    }
    
    private void configureLayout(){
        //Posicionar etiqueta nombre
        layout.putConstraint(SpringLayout.EAST, nombre,
                     -10,
                     SpringLayout.HORIZONTAL_CENTER, this);
        layout.putConstraint(SpringLayout.VERTICAL_CENTER, nombre,
                     -30,
                     SpringLayout.VERTICAL_CENTER, this);
        //Posicionar etiqueta contraseña
        layout.putConstraint(SpringLayout.EAST, contrasena,
                     -10,
                     SpringLayout.HORIZONTAL_CENTER, this);
        layout.putConstraint(SpringLayout.VERTICAL_CENTER, contrasena,
                     0,
                     SpringLayout.VERTICAL_CENTER, this);
        //Posicionar campo nombre
        layout.putConstraint(SpringLayout.WEST, fnombre,
                     10,
                     SpringLayout.HORIZONTAL_CENTER, this);
        layout.putConstraint(SpringLayout.VERTICAL_CENTER, fnombre,
                     -30,
                     SpringLayout.VERTICAL_CENTER, this);
        
        //Posicionar campo contraseña
        layout.putConstraint(SpringLayout.WEST, fcontrasena,
                     10,
                     SpringLayout.HORIZONTAL_CENTER, this);
        layout.putConstraint(SpringLayout.VERTICAL_CENTER, fcontrasena,
                     0,
                     SpringLayout.VERTICAL_CENTER, this);

        //Posicionar el boton
        layout.putConstraint(SpringLayout.HORIZONTAL_CENTER, enviar,
                     0,
                     SpringLayout.HORIZONTAL_CENTER, this);
        layout.putConstraint(SpringLayout.VERTICAL_CENTER, enviar,
                     30,
                     SpringLayout.VERTICAL_CENTER, this);
    }
    
    private class EnviarPress implements ActionListener {
        public EnviarPress() {
        }
        @Override
        public void actionPerformed(ActionEvent e){
            boolean respuesta;
            try {
                respuesta = padre.getPrograma().LoginConection(Long.valueOf(fnombre.getText()), fcontrasena.getText());
            }
            catch (Exception ex){
                respuesta = false;
            }
            
            if(respuesta){
                padre.CambiarPanel("login", "menu");
            }
            //Quizas convendria un mensaje de error
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
